nightly pipeline: preinstall TF CLI to workaround installation error

diff --git a/.azdo/nightly-test-pipeline.yml b/.azdo/nightly-test-pipeline.yml
--- a/.azdo/nightly-test-pipeline.yml
+++ b/.azdo/nightly-test-pipeline.yml
@@ -14,6 +14,20 @@ jobs:
           GOPATH: "$(Pipeline.Workspace)/gopath"
           GOBIN: "$(GOPATH)/bin"
 
+      - task: TerraformInstaller@1
+        displayName: "Install Terraform"
+        inputs:
+          terraformVersion: "1.15.1"
+
+      - bash: |
+          #!/usr/bin/env bash
+          set -euo pipefail
+          terraform_path="$(which terraform)"
+          echo "Terraform installed at: ${terraform_path}"
+          echo "Overriding terraform CLI for acctest to workaround the error: 'cannot run Terraform provider tests: failed to find or install Terraform CLI from [0xc000130100 0xc000154000]: unable to verify checksums signature: openpgp: key expired'"
+          echo "##vso[task.setvariable variable=TF_ACC_TERRAFORM_PATH]${terraform_path}"
+        displayName: "Configure Terraform CLI for acctest"
+
       - bash: |
           #!/usr/bin/env bash
           make tools
@@ -43,4 +57,5 @@ jobs:
           ARM_CLIENT_ID: $(ARM_CLIENT_ID)
           ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
           ARM_TENANT_ID: $(ARM_TENANT_ID)
+          TF_ACC_TERRAFORM_PATH: $(TF_ACC_TERRAFORM_PATH)
           TESTARGS: $(TESTARGS)
